version: '3'
services:
  mysql:
    image: "mysql:5.7.10"
    container_name: "ocr"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "riiid"
      MYSQL_DATABASE: "ocr"
    volumes:
      - bp_db:/var/lib/mysql
    networks: # 서버와 같은 네트워크, 잊지 마세요!
      - backend
networks:
  backend:
    driver: bridge
volumes:
  bp_db:
    driver: "local"
